# 状态栏设置
# 设置tmux窗口列表，显示到状态栏中间
set-option -g status-justify centre

# 设置状态栏中当前活动窗口的对应的标签为蓝色
setw -g window-status-current-style "bg=blue, fg=white"
setw -g window-status-style "fg=black"

# 设置窗口列表的分隔符为“|”
setw -g window-status-separator  '|'

# 设置状态栏显示的窗口编号起始号码为1
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on


# 状态栏整体刷新时间
set-option -g status-interval 1
# 状态栏左侧内容颜色及最大长度
# set-option -g status-left "#(~/.config/tmux/net.sh) #(~/.config/tmux/mem.sh) #(~/code/.config/tmux/process.sh)"
set-option -g status-left "#(~/.config/tmux/mem.sh) #(~/.config/tmux/process.sh) #(~/.config/tmux/disk.sh)"
set-option -g status-left-style "bg=magenta fg=black"
set-option -g status-left-length 90
# 状态栏右内容颜色及最大长度
set-option -g status-right-style "bg=yellow"

# 设定tmux窗格的缓冲区最多缓冲的行数
set-option -g history-limit 5000000

# 使能鼠标，鼠标启动后，可以按下shift来恢复原本的操作
set-option -g mouse on

# tmux取消Leader+Space切换pane布局
unbind Space

# 设置终端支持256color
set -g default-terminal "screen-256color"

# 设置alt+hjkl四个按键为切换当前焦点pane为左下上右四个方向的pane
# 使用 Alt + h, j, k, l 来移动pane
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
